apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/load-balancer-type":"Internal"},"name":"mllp-adapter-service","namespace":"default"},"spec":{"ports":[{"name":"port","port":2575,"protocol":"TCP","targetPort":2575}],"selector":{"app":"mllp-adapter"},"type":"LoadBalancer"}}
  creationTimestamp: "2021-02-06T03:22:13Z"
  finalizers:
  - gke.networking.io/l4-ilb-v1
  - service.kubernetes.io/load-balancer-cleanup
  name: mllp-adapter-service
  namespace: default
  resourceVersion: "13490"
  selfLink: /api/v1/namespaces/default/services/mllp-adapter-service
  uid: 9a195a46-4ed7-4bc7-994e-a332f24606ce
spec:
  clusterIP: 10.4.7.154
  externalTrafficPolicy: Cluster
  ports:
  - name: port
    nodePort: 32195
    port: 2575
    protocol: TCP
    targetPort: 2575
  selector:
    app: mllp-adapter
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.128.0.15
