apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"mllp-adapter-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mllp-adapter"}},"template":{"metadata":{"labels":{"app":"mllp-adapter"}},"spec":{"containers":[{"command":["/usr/mllp_adapter/mllp_adapter","--port=2575","--hl7_v2_project_id=uottahack4","--hl7_v2_location_id=northamerica-northeast1","--hl7_v2_dataset_id=hl7","--hl7_v2_store_id=hl7-mllp","--api_addr_prefix=https://healthcare.googleapis.com:443/v1","--logtostderr","--receiver_ip=0.0.0.0"],"image":"gcr.io/cloud-healthcare-containers/mllp-adapter","imagePullPolicy":"Always","name":"mllp-adapter","ports":[{"containerPort":2575,"name":"port","protocol":"TCP"}]}]}}}}
  creationTimestamp: "2021-02-06T03:33:42Z"
  generation: 2
  name: mllp-adapter-deployment
  namespace: default
  resourceVersion: "18146"
  selfLink: /apis/apps/v1/namespaces/default/deployments/mllp-adapter-deployment
  uid: b0eb367f-8fab-4ab1-8a6c-3b2c94bff86d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mllp-adapter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mllp-adapter
    spec:
      containers:
      - command:
        - /usr/mllp_adapter/mllp_adapter
        - --port=2575
        - --hl7_v2_project_id=uottahack4
        - --hl7_v2_location_id=northamerica-northeast1
        - --hl7_v2_dataset_id=hl7
        - --hl7_v2_store_id=hl7-mllp
        - --api_addr_prefix=https://healthcare.googleapis.com:443/v1
        - --logtostderr
        - --receiver_ip=0.0.0.0
        image: gcr.io/cloud-healthcare-containers/mllp-adapter
        imagePullPolicy: Always
        name: mllp-adapter
        ports:
        - containerPort: 2575
          name: port
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-02-06T03:35:49Z"
    lastUpdateTime: "2021-02-06T03:35:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-02-06T03:33:42Z"
    lastUpdateTime: "2021-02-06T03:35:49Z"
    message: ReplicaSet "mllp-adapter-deployment-5fdb9759c9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
